FROM node:20-bullseye AS builder

WORKDIR /app

RUN npm install -g hexo-cli

COPY package*.json ./
RUN npm install

COPY . .
RUN hexo clean && hexo generate

FROM nginx

COPY --from=builder /app/public /usr/share/nginx/html
